CREATE TABLE IF NOT EXISTS `accounting_paypal_imports` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `original_filename` varchar(255) NOT NULL,
  `file_hash` char(64) NOT NULL,
  `detected_encoding` varchar(32) DEFAULT NULL,
  `detected_delimiter` varchar(8) DEFAULT NULL,
  `header_json` longtext NOT NULL,
  `source_row_count` int unsigned NOT NULL DEFAULT 0,
  `imported_row_count` int unsigned NOT NULL DEFAULT 0,
  `duplicate_row_count` int unsigned NOT NULL DEFAULT 0,
  `matched_transaction_count` int unsigned NOT NULL DEFAULT 0,
  `review_transaction_count` int unsigned NOT NULL DEFAULT 0,
  `imported_by` int DEFAULT NULL,
  `imported_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_accounting_paypal_import_hash` (`file_hash`),
  KEY `ix_accounting_paypal_imported_at` (`imported_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `accounting_paypal_transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `import_id` bigint unsigned NOT NULL,
  `source_key` char(64) NOT NULL,
  `source_row_number` int unsigned NOT NULL,
  `transaction_date` date DEFAULT NULL,
  `transaction_time` time DEFAULT NULL,
  `payer_name` varchar(255) DEFAULT NULL,
  `transaction_type` varchar(128) DEFAULT NULL,
  `transaction_status` varchar(64) DEFAULT NULL,
  `currency` varchar(8) DEFAULT NULL,
  `gross_amount` decimal(16,2) DEFAULT NULL,
  `fee_amount` decimal(16,2) DEFAULT NULL,
  `net_amount` decimal(16,2) DEFAULT NULL,
  `payer_email` varchar(255) DEFAULT NULL,
  `transaction_id` varchar(128) DEFAULT NULL,
  `reference_transaction_id` varchar(128) DEFAULT NULL,
  `raw_invoice_number` varchar(255) DEFAULT NULL,
  `item_title` text DEFAULT NULL,
  `subject_text` text DEFAULT NULL,
  `note_text` text DEFAULT NULL,
  `balance_impact` varchar(32) DEFAULT NULL,
  `matched_order_id` bigint DEFAULT NULL,
  `matched_custom_order_id` bigint DEFAULT NULL,
  `matched_custom_code` varchar(64) DEFAULT NULL,
  `export_order_number` varchar(128) DEFAULT NULL,
  `match_method` varchar(64) DEFAULT NULL,
  `match_confidence` tinyint unsigned NOT NULL DEFAULT 0,
  `manual_override` tinyint(1) NOT NULL DEFAULT 0,
  `raw_json` longtext NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_accounting_paypal_source_key` (`source_key`),
  KEY `ix_accounting_paypal_date` (`transaction_date`),
  KEY `ix_accounting_paypal_transaction` (`transaction_id`),
  KEY `ix_accounting_paypal_reference` (`reference_transaction_id`),
  KEY `ix_accounting_paypal_export_number` (`export_order_number`),
  KEY `ix_accounting_paypal_import` (`import_id`),
  CONSTRAINT `fk_accounting_paypal_import`
    FOREIGN KEY (`import_id`) REFERENCES `accounting_paypal_imports` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
