CREATE TABLE IF NOT EXISTS accounting_payout_imports (
  id BIGINT NOT NULL AUTO_INCREMENT,
  original_filename VARCHAR(255) NOT NULL,
  file_hash CHAR(64) NOT NULL,
  source_region VARCHAR(8) NOT NULL,
  detected_encoding VARCHAR(32) DEFAULT NULL,
  detected_delimiter VARCHAR(8) DEFAULT NULL,
  source_row_count INT NOT NULL DEFAULT 0,
  imported_row_count INT NOT NULL DEFAULT 0,
  duplicate_row_count INT NOT NULL DEFAULT 0,
  matched_order_count INT NOT NULL DEFAULT 0,
  imported_by INT DEFAULT NULL,
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_accounting_payout_import_hash (file_hash),
  KEY ix_accounting_payout_imported_at (imported_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS accounting_payout_transactions (
  id BIGINT NOT NULL AUTO_INCREMENT,
  import_id BIGINT NOT NULL,
  source_key CHAR(64) NOT NULL,
  source_region VARCHAR(8) NOT NULL,
  transaction_date DATE DEFAULT NULL,
  transaction_type VARCHAR(32) NOT NULL,
  transaction_type_raw VARCHAR(80) DEFAULT NULL,
  order_number VARCHAR(128) DEFAULT NULL,
  legacy_order_id VARCHAR(128) DEFAULT NULL,
  buyer_username VARCHAR(255) DEFAULT NULL,
  buyer_name VARCHAR(255) DEFAULT NULL,
  post_country VARCHAR(16) DEFAULT NULL,
  net_amount DECIMAL(14,2) DEFAULT NULL,
  payout_currency VARCHAR(8) DEFAULT NULL,
  payout_date DATE DEFAULT NULL,
  payout_id VARCHAR(128) DEFAULT NULL,
  payout_status VARCHAR(128) DEFAULT NULL,
  item_id VARCHAR(128) DEFAULT NULL,
  transaction_id VARCHAR(128) DEFAULT NULL,
  item_title TEXT DEFAULT NULL,
  custom_label VARCHAR(255) DEFAULT NULL,
  quantity DECIMAL(12,3) DEFAULT NULL,
  item_subtotal DECIMAL(14,2) DEFAULT NULL,
  postage DECIMAL(14,2) DEFAULT NULL,
  seller_collected_tax DECIMAL(14,2) DEFAULT NULL,
  ebay_collected_tax DECIMAL(14,2) DEFAULT NULL,
  fixed_fee DECIMAL(14,4) DEFAULT NULL,
  variable_fee DECIMAL(14,4) DEFAULT NULL,
  regulatory_fee DECIMAL(14,4) DEFAULT NULL,
  very_high_inad_fee DECIMAL(14,4) DEFAULT NULL,
  below_standard_fee DECIMAL(14,4) DEFAULT NULL,
  international_fee DECIMAL(14,4) DEFAULT NULL,
  gross_transaction_amount DECIMAL(14,2) DEFAULT NULL,
  transaction_currency VARCHAR(8) DEFAULT NULL,
  exchange_rate DECIMAL(16,8) DEFAULT NULL,
  gross_payout_amount DECIMAL(14,2) DEFAULT NULL,
  fee_payout_amount DECIMAL(14,2) DEFAULT NULL,
  reconciliation_difference DECIMAL(14,2) DEFAULT NULL,
  reference_id VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  matched_order_id BIGINT DEFAULT NULL,
  raw_json LONGTEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_accounting_payout_source_key (source_key),
  KEY ix_accounting_payout_import (import_id),
  KEY ix_accounting_payout_order (order_number),
  KEY ix_accounting_payout_date_type (transaction_date, transaction_type),
  KEY ix_accounting_payout_payout_id (payout_id),
  KEY ix_accounting_payout_matched_order (matched_order_id),
  CONSTRAINT fk_accounting_payout_import FOREIGN KEY (import_id)
    REFERENCES accounting_payout_imports(id) ON DELETE CASCADE,
  CONSTRAINT fk_accounting_payout_order FOREIGN KEY (matched_order_id)
    REFERENCES orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

